# Generated by Django 5.0 on 2023-12-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0002_remove_contacts_description_remove_contacts_is_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
