# Generated by Django 5.0 on 2023-12-05 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contacts_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='phone_number',
        ),
    ]
