# Generated by Django 5.0 on 2023-12-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contacts_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=12),
        ),
    ]
