# Generated by Django 5.0 on 2023-12-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contacts_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='notes',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(default='+1', max_length=12),
        ),
    ]
