# Generated by Django 5.0 on 2023-12-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contacts_notes_alter_contacts_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='Contact',
        ),
    ]
